//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAvail.MVC.Bootstrap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BootstrapHelperResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BootstrapHelperResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAvail.MVC.Bootstrap.BootstrapHelperResources", typeof(BootstrapHelperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;control-group&quot;&gt;
        ///    &lt;div class=&quot;controls&quot;&gt;
        ///        &lt;label class=&quot;checkbox&quot;&gt;
        ///            &lt;input type=&quot;checkbox&quot; data-bind=&quot;checked : useRepeatCreate&quot;&gt;
        ///            {0}
        ///        &lt;/label&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string CreateAndContinue {
            get {
                return ResourceManager.GetString("CreateAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;modal hide&quot; data-form-type=&quot;create&quot; data-form-resource=&quot;{0}&quot;&gt;
        ///    &lt;div class=&quot;modal-header&quot;&gt;
        ///        &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;modal&quot; aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/button&gt;
        ///        &lt;h3&gt;Новый {2}&lt;/h3&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;modal-body&quot;&gt;
        ///        &lt;form class=&quot;form-horizontal&quot; action=&quot;#&quot;&gt;
        ///            {1}
        ///        &lt;/form&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;modal-footer&quot;&gt;
        ///        &lt;a href=&quot;#&quot; class=&quot;btn&quot; data-bind=&quot;click : cancel&quot;&gt;Закрыть&lt;/a&gt;
        ///        &lt;a href=&quot;#&quot; class=&quot;btn b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateFrorm {
            get {
                return ResourceManager.GetString("CreateFrorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;modal hide&quot; data-form-type=&quot;update&quot; data-form-resource=&quot;{0}&quot;&gt;
        ///    &lt;div class=&quot;modal-header&quot;&gt;
        ///        &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;modal&quot; aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/button&gt;
        ///        &lt;h3&gt;Изменить {2}&lt;/h3&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;modal-body&quot;&gt;
        ///        &lt;form class=&quot;form-horizontal&quot; action=&quot;#&quot;&gt;
        ///            {1}
        ///        &lt;/form&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;modal-footer&quot;&gt;
        ///        &lt;a href=&quot;#&quot; class=&quot;btn btn-warning pull-left&quot; data-bind=&quot;click : remove&quot;&gt;Удалить {2}&lt;/a&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditFrorm {
            get {
                return ResourceManager.GetString("EditFrorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form class=&quot;form-horizontal&quot; action=&quot;#&quot;&gt;
        ///    {0}
        ///    &lt;div class=&quot;control-group&quot;&gt;
        ///        &lt;div class=&quot;controls&quot;&gt;
        ///            &lt;button type=&quot;submit&quot; class=&quot;btn&quot; data-bind=&quot;click: update&quot;&gt;Сохранить&lt;/button&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/form&gt;
        ///.
        /// </summary>
        internal static string EditFrormEmbed {
            get {
                return ResourceManager.GetString("EditFrormEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;table table-striped&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            {0}
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody data-bind=&quot;template: {name : &apos;{2}-row&apos;, foreach : list}&quot;&gt;
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;
        ///
        ///&lt;script type=&quot;text/html&quot; id=&quot;{2}-row&quot;&gt;
        ///    &lt;tr data-bind=&quot;click: startUpdate&quot;&gt;
        ///        {1}
        ///        &lt;td&gt;{3}&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/script&gt;
        ///.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#&quot; data-bind=&quot;click: details&quot; data-bind-event=&quot;details&quot;&gt;&lt;i class=&quot;icon-pencil&quot;&gt;&lt;/i&gt;&amp;nbsp;подробно&lt;/a&gt;.
        /// </summary>
        internal static string TableOpers {
            get {
                return ResourceManager.GetString("TableOpers", resourceCulture);
            }
        }
    }
}
